import {
  authenticateNativeRequest,
  nativeErrorResponse,
} from "@/lib/native-auth";
import { logAdminAction, requireSuperAdmin } from "@/lib/super-admin";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

interface PlaceholderSpec {
  displayName: string;
  relationshipLabel: string;
  isMinor?: boolean;
  /** Index of the parent in this same list (after the owner). */
  managedByIndex?: number;
  /** Edge to draw between owner (index = -1) or another placeholder (index >= 0). */
  edge: { otherIndex: number; kind: string };
}

const DEFAULT_FAMILY: PlaceholderSpec[] = [
  {
    displayName: "Mom (test)",
    relationshipLabel: "Mom",
    edge: { otherIndex: -1, kind: "parent" },
  },
  {
    displayName: "Dad (test)",
    relationshipLabel: "Dad",
    edge: { otherIndex: -1, kind: "parent" },
  },
  {
    displayName: "Sibling (test)",
    relationshipLabel: "Sibling",
    edge: { otherIndex: -1, kind: "sibling" },
  },
  {
    displayName: "Cousin (test)",
    relationshipLabel: "Cousin",
    edge: { otherIndex: -1, kind: "cousin" },
  },
  {
    displayName: "Grandparent (test)",
    relationshipLabel: "Grandparent",
    edge: { otherIndex: -1, kind: "grandparent" },
  },
];

export async function POST(request: Request) {
  try {
    const { user, supabase } = await authenticateNativeRequest(request);
    await requireSuperAdmin(supabase, user.id);
    const admin = createSupabaseAdminClient();

    const stamp = new Date().toISOString().slice(0, 16).replace("T", " ");
    const circleName = `Test Family ⌚ ${stamp}`;

    const circleInsert = await admin
      .from("family_circles")
      .insert({
        name: circleName,
        description:
          "Generated by the super-admin testing toolkit. Safe to delete.",
        created_by: user.id,
      })
      .select("id")
      .single();
    if (circleInsert.error || !circleInsert.data) {
      return Response.json(
        { error: circleInsert.error?.message ?? "Failed to create circle" },
        { status: 500 }
      );
    }
    const circleId = circleInsert.data.id;

    // Owner membership (the calling super admin).
    const profileResponse = await admin
      .from("profiles")
      .select("full_name, timezone")
      .eq("id", user.id)
      .maybeSingle();
    const ownerName =
      (profileResponse.data as { full_name: string | null } | null)
        ?.full_name ?? "Test Admin";
    const ownerInsert = await admin
      .from("family_memberships")
      .insert({
        family_circle_id: circleId,
        user_id: user.id,
        display_name: `${ownerName} (you)`,
        relationship_label: "Self",
        status: "active",
        role: "owner",
      })
      .select("id")
      .single();
    if (ownerInsert.error || !ownerInsert.data) {
      return Response.json(
        { error: ownerInsert.error?.message ?? "Failed to add owner" },
        { status: 500 }
      );
    }
    const ownerMembershipId = ownerInsert.data.id;

    // Placeholder members.
    const placeholderIds: string[] = [];
    for (const spec of DEFAULT_FAMILY) {
      const insert = await admin
        .from("family_memberships")
        .insert({
          family_circle_id: circleId,
          display_name: spec.displayName,
          relationship_label: spec.relationshipLabel,
          status: "active",
          role: "member",
          is_placeholder: true,
          is_minor: spec.isMinor ?? false,
          managed_by_membership_id:
            spec.managedByIndex !== undefined
              ? placeholderIds[spec.managedByIndex] ?? ownerMembershipId
              : null,
        })
        .select("id")
        .single();
      if (insert.error || !insert.data) {
        return Response.json(
          { error: insert.error?.message ?? "Failed to add member" },
          { status: 500 }
        );
      }
      placeholderIds.push(insert.data.id);
    }

    // Relationship edges. otherIndex -1 means edge to the owner.
    const edgesPayload = DEFAULT_FAMILY.map((spec, idx) => {
      const otherId =
        spec.edge.otherIndex === -1
          ? ownerMembershipId
          : placeholderIds[spec.edge.otherIndex];
      return {
        family_circle_id: circleId,
        source_membership_id: placeholderIds[idx],
        target_membership_id: otherId,
        kind: spec.edge.kind,
      };
    });
    if (edgesPayload.length) {
      await admin.from("relationship_edges").insert(edgesPayload);
    }

    // Availability windows: weekdays 18:00–21:00 for everyone with a user_id.
    // Placeholders have no user_id so they can't have windows under the
    // existing schema (availability_windows.user_id NOT NULL). Owner gets
    // the windows; placeholders rely on the engine treating them as
    // perma-available because they have no windows? Actually the engine
    // requires availability — so for the test family we instead insert
    // synthetic placeholder rows by reusing the owner's user_id. That's
    // fine for an internal test fixture.
    const availabilityRows: Array<{
      family_circle_id: string;
      membership_id: string;
      user_id: string;
      weekday: number;
      start_hour: number;
      end_hour: number;
    }> = [];
    const allMembershipIds = [ownerMembershipId, ...placeholderIds];
    for (const mid of allMembershipIds) {
      for (let weekday = 1; weekday <= 5; weekday += 1) {
        availabilityRows.push({
          family_circle_id: circleId,
          membership_id: mid,
          user_id: user.id,
          weekday,
          start_hour: 18,
          end_hour: 21,
        });
      }
    }
    if (availabilityRows.length) {
      await admin.from("availability_windows").insert(availabilityRows);
    }

    await logAdminAction(admin, {
      actorUserId: user.id,
      kind: "test_fixture.family_created",
      targetCircleId: circleId,
      payload: { memberCount: allMembershipIds.length, name: circleName },
    });

    return Response.json({
      success: true,
      circleId,
      circleName,
      memberCount: allMembershipIds.length,
    });
  } catch (error) {
    return nativeErrorResponse(error);
  }
}
