import {
  authenticateNativeRequest,
  nativeErrorResponse,
} from "@/lib/native-auth";
import { getViewerFamilyCircleWith } from "@/lib/data";

export async function POST(
  request: Request,
  context: { params: Promise<{ id: string }> }
) {
  try {
    const { user, supabase } = await authenticateNativeRequest(request);
    const { id } = await context.params;

    const family = await getViewerFamilyCircleWith(supabase, user.id);
    if (
      !family ||
      family.membership.status !== "active" ||
      family.membership.role !== "owner"
    ) {
      return Response.json(
        { error: "Only the family circle owner can cancel recurring calls." },
        { status: 403 }
      );
    }

    const updateRule = await supabase
      .from("call_recurrence_rules")
      .update({ active: false })
      .eq("id", id)
      .eq("family_circle_id", family.circle.id);
    if (updateRule.error) {
      return Response.json(
        { error: updateRule.error.message },
        { status: 400 }
      );
    }

    // Cancel all future scheduled instances generated by this rule.
    await supabase
      .from("call_sessions")
      .update({ status: "canceled", reminder_status: "not_needed" })
      .eq("recurrence_rule_id", id)
      .gte("scheduled_start", new Date().toISOString())
      .in("status", ["scheduled"]);

    return Response.json({ success: true });
  } catch (error) {
    return nativeErrorResponse(error);
  }
}
