-- M18 — recurring calls
-- Stores rules for repeating family calls (weekly / biweekly / monthly).
-- A rolling 4-week horizon of materialized call_sessions is generated by
-- the daily /api/cron/recurrence-materialize sweep.

create table if not exists public.call_recurrence_rules (
  id                            uuid primary key default gen_random_uuid(),
  family_circle_id              uuid not null references public.family_circles(id) on delete cascade,
  title                         text not null,
  description                   text,
  -- 'weekly' | 'biweekly' | 'monthly'
  frequency                     text not null check (frequency in ('weekly','biweekly','monthly')),
  -- 0=Sun..6=Sat for weekly/biweekly
  day_of_week                   int  check (day_of_week between 0 and 6),
  -- 1..31 for monthly
  day_of_month                  int  check (day_of_month between 1 and 31),
  start_local_time              time not null,
  duration_minutes              int  not null default 30 check (duration_minutes between 5 and 480),
  timezone                      text not null,
  active                        boolean not null default true,
  created_by_membership_id      uuid references public.family_memberships(id) on delete set null,
  created_at                    timestamptz not null default now(),
  -- Tracks how far forward we've already materialized call_sessions
  last_materialized_through     timestamptz
);

create index if not exists call_recurrence_rules_circle_active_idx
  on public.call_recurrence_rules (family_circle_id, active);

alter table public.call_sessions add column if not exists recurrence_rule_id uuid
  references public.call_recurrence_rules(id) on delete set null;

create index if not exists call_sessions_recurrence_idx
  on public.call_sessions (recurrence_rule_id);

-- ── RLS ─────────────────────────────────────────────────────────────────────

alter table public.call_recurrence_rules enable row level security;

create policy "call_recurrence_rules_select"
  on public.call_recurrence_rules
  for select
  to authenticated
  using (family_circle_id in (select public.get_my_family_circle_ids()));

create policy "call_recurrence_rules_owner_write"
  on public.call_recurrence_rules
  for all
  to authenticated
  using (
    family_circle_id in (
      select id from public.family_circles where created_by = auth.uid()
    )
  )
  with check (
    family_circle_id in (
      select id from public.family_circles where created_by = auth.uid()
    )
  );
